layout_spectrum: 0.9693877
typography_spectrum: 0.6954887
color:
  saturation: 0.04277354
  lightness: 0.9533323
  brandStrength: 0.9198419
  rhythmicContrast: 0.5747022
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: "Walters' Tree"
