name: "Walters' Tree"
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.6954887
title: "Walters' Tree "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5b5b7'
    - '#598699'
    - '#0e0e10'
    - '#244d5f'
    - '#ebf8fe'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
